version: "3.9"
services:

  mysql-api:
    image: mysql
    container_name: mysql-container
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pcmatogrosso
